name: Maven Build

on:
  push:
    branches: [ autotool ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Manual trigger option

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Run Tests
      run: mvn test
      
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: AntiCheatAddition
        path: target/AntiCheatAddition-*.jar