name: Build AntiCheatAddition

on:
  push:
    branches: [ main, master, dev, autotool ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Test with Maven
      run: mvn test
      
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: AntiCheatAddition
        path: target/AntiCheatAddition-*.jar
        
  # Optional: Add code quality checks
  code-quality:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Check code style
      run: mvn checkstyle:check
      continue-on-error: true  # Don't fail the build for style issues