name: Build AntiCheatAddition

on:
  # build EVERY branch that is pushed – including "autotoolyay"
  push:
    branches: [ '**' ]

  # build every pull-request, no matter which branch it targets
  pull_request:
    branches: [ '**' ]

  # manual run button in the Actions tab
  workflow_dispatch:

  # run again when a new GitHub release is created (for publishing)
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Temurin JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '21'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: AntiCheatAddition
        path: target/AntiCheatAddition-*.jar

    # ───────── Publish to GitHub Packages only on releases ─────────
    - name: Configure Maven for GitHub Packages
      if: github.event_name == 'release'
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '21'
        server-id: github          # matches <id>github</id> in pom/settings.xml
        settings-path: ${{ github.workspace }}

    - name: Deploy to GitHub Packages
      if: github.event_name == 'release'
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
